### ISSUE TITLE
.rnc File Changes

### ISSUE THREAD

**Issue by enb34** [enb34/alice-in-translation#6]
Due to the fact that we will be checking for similarities in both of the English version and the Japanese version of the text, it seems important that we keep the schema for both of these documents consistent. When naming the schema, I kept the name the same as the English version XML file, which overlooks that there will be another XML file with a different name. I have changed the name of the schema to reflect this, from alice-fullwork-english.rnc to simply alice-fullwork.rnc, by saving all my new changes under a new file name. Both files are currently part of the repo.

I was wondering if there was a way to delete the original schema (alice-fullwork-english.rnc) from the repo to reduce clutter. I didn't want to try anything without consulting someone with more experience first--I didn't want to mess anything up (again, whoops). Can I just delete this file from my own cloned repo and push to the master branch, or is there a different process I should do instead?

**Comment by djbpitt** [comment]
@enb34 Your last sentence says it all! If you delete a file in your local (cloned) repo, commit your changes, and push, it will remove the file from the project on GitHub, and when your project partner pulls from GitHub, it will disappear from her local clone, as well. 

For what it's worth, nothing is ever truly removed from a GitHub repo because git supports infinite "undo". But the deleted file will disappear from view, so you'll reduce the clutter, and you won't see it again unless you go looking for it explicitly through the undo mechanism.

**Comment by enb34** [comment]
@djbpitt Thanks! I made the change to the repo.
